// Code generated by MockGen. DO NOT EDIT.
// Source: ./message_encoder.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	message "github.com/topfreegames/pitaya/v3/pkg/conn/message"
)

// MockEncoder is a mock of Encoder interface
type MockEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderMockRecorder
}

// MockEncoderMockRecorder is the mock recorder for MockEncoder
type MockEncoderMockRecorder struct {
	mock *MockEncoder
}

// NewMockEncoder creates a new mock instance
func NewMockEncoder(ctrl *gomock.Controller) *MockEncoder { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEncoder) EXPECT() *MockEncoderMockRecorder {
	_ = "STUB: not implemented"

	// IsCompressionEnabled mocks base method
	return nil
}

func (m *MockEncoder) IsCompressionEnabled() bool { _ = "STUB: not implemented"; return false }

// IsCompressionEnabled indicates an expected call of IsCompressionEnabled
func (mr *MockEncoderMockRecorder) IsCompressionEnabled() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Encode mocks base method
func (m *MockEncoder) Encode(message *message.Message) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Encode indicates an expected call of Encode
func (mr *MockEncoderMockRecorder) Encode(message interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
