// Code generated by MockGen. DO NOT EDIT.
// Source: conn/codec/packet_decoder.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	packet "github.com/topfreegames/pitaya/v3/pkg/conn/packet"
)

// MockPacketDecoder is a mock of PacketDecoder interface
type MockPacketDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockPacketDecoderMockRecorder
}

// MockPacketDecoderMockRecorder is the mock recorder for MockPacketDecoder
type MockPacketDecoderMockRecorder struct {
	mock *MockPacketDecoder
}

// NewMockPacketDecoder creates a new mock instance
func NewMockPacketDecoder(ctrl *gomock.Controller) *MockPacketDecoder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPacketDecoder) EXPECT() *MockPacketDecoderMockRecorder {
	_ = "STUB: not implemented"

	// Decode mocks base method
	return nil
}

func (m *MockPacketDecoder) Decode(data []byte) ([]*packet.Packet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Decode indicates an expected call of Decode
func (mr *MockPacketDecoderMockRecorder) Decode(data interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
