// Code generated by MockGen. DO NOT EDIT.
// Source: conn/codec/packet_encoder.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	packet "github.com/topfreegames/pitaya/v3/pkg/conn/packet"
)

// MockPacketEncoder is a mock of PacketEncoder interface
type MockPacketEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockPacketEncoderMockRecorder
}

// MockPacketEncoderMockRecorder is the mock recorder for MockPacketEncoder
type MockPacketEncoderMockRecorder struct {
	mock *MockPacketEncoder
}

// NewMockPacketEncoder creates a new mock instance
func NewMockPacketEncoder(ctrl *gomock.Controller) *MockPacketEncoder {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPacketEncoder) EXPECT() *MockPacketEncoderMockRecorder {
	_ = "STUB: not implemented"

	// Encode mocks base method
	return nil
}

func (m *MockPacketEncoder) Encode(typ packet.Type, data []byte) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Encode indicates an expected call of Encode
func (mr *MockPacketEncoderMockRecorder) Encode(typ, data interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
