// Code generated by MockGen. DO NOT EDIT.
// Source: protos/pitaya.pb.go

// Package mock_protos is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	protos "github.com/topfreegames/pitaya/v3/pkg/protos"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// MockPitayaClient is a mock of PitayaClient interface.
type MockPitayaClient struct {
	ctrl     *gomock.Controller
	recorder *MockPitayaClientMockRecorder
}

// MockPitayaClientMockRecorder is the mock recorder for MockPitayaClient.
type MockPitayaClientMockRecorder struct {
	mock *MockPitayaClient
}

// NewMockPitayaClient creates a new mock instance.
func NewMockPitayaClient(ctrl *gomock.Controller) *MockPitayaClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPitayaClient) EXPECT() *MockPitayaClientMockRecorder {
	_ = "STUB: not implemented"

	// Call mocks base method.
	return nil
}

func (m *MockPitayaClient) Call(ctx context.Context, in *protos.Request, opts ...grpc.CallOption) (*protos.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Call indicates an expected call of Call.
func (mr *MockPitayaClientMockRecorder) Call(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// KickUser mocks base method.
func (m *MockPitayaClient) KickUser(ctx context.Context, in *protos.KickMsg, opts ...grpc.CallOption) (*protos.KickAnswer, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// KickUser indicates an expected call of KickUser.
func (mr *MockPitayaClientMockRecorder) KickUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PushToUser mocks base method.
func (m *MockPitayaClient) PushToUser(ctx context.Context, in *protos.Push, opts ...grpc.CallOption) (*protos.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PushToUser indicates an expected call of PushToUser.
func (mr *MockPitayaClientMockRecorder) PushToUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SessionBindRemote mocks base method.
func (m *MockPitayaClient) SessionBindRemote(ctx context.Context, in *protos.BindMsg, opts ...grpc.CallOption) (*protos.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SessionBindRemote indicates an expected call of SessionBindRemote.
func (mr *MockPitayaClientMockRecorder) SessionBindRemote(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockPitayaServer is a mock of PitayaServer interface.
type MockPitayaServer struct {
	ctrl     *gomock.Controller
	recorder *MockPitayaServerMockRecorder
}

// MockPitayaServerMockRecorder is the mock recorder for MockPitayaServer.
type MockPitayaServerMockRecorder struct {
	mock *MockPitayaServer
}

// NewMockPitayaServer creates a new mock instance.
func NewMockPitayaServer(ctrl *gomock.Controller) *MockPitayaServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPitayaServer) EXPECT() *MockPitayaServerMockRecorder {
	_ = "STUB: not implemented"

	// Call mocks base method.
	return nil
}

func (m *MockPitayaServer) Call(arg0 context.Context, arg1 *protos.Request) (*protos.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Call indicates an expected call of Call.
func (mr *MockPitayaServerMockRecorder) Call(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// KickUser mocks base method.
func (m *MockPitayaServer) KickUser(arg0 context.Context, arg1 *protos.KickMsg) (*protos.KickAnswer, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// KickUser indicates an expected call of KickUser.
func (mr *MockPitayaServerMockRecorder) KickUser(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PushToUser mocks base method.
func (m *MockPitayaServer) PushToUser(arg0 context.Context, arg1 *protos.Push) (*protos.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PushToUser indicates an expected call of PushToUser.
func (mr *MockPitayaServerMockRecorder) PushToUser(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SessionBindRemote mocks base method.
func (m *MockPitayaServer) SessionBindRemote(arg0 context.Context, arg1 *protos.BindMsg) (*protos.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SessionBindRemote indicates an expected call of SessionBindRemote.
func (mr *MockPitayaServerMockRecorder) SessionBindRemote(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
