// Code generated by MockGen. DO NOT EDIT.
// Source: cluster/cluster.go

// Package mock_cluster is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	cluster "github.com/topfreegames/pitaya/v3/pkg/cluster"
	message "github.com/topfreegames/pitaya/v3/pkg/conn/message"
	protos "github.com/topfreegames/pitaya/v3/pkg/protos"
	route "github.com/topfreegames/pitaya/v3/pkg/route"
	session "github.com/topfreegames/pitaya/v3/pkg/session"
)

// MockRPCServer is a mock of RPCServer interface.
type MockRPCServer struct {
	ctrl     *gomock.Controller
	recorder *MockRPCServerMockRecorder
}

// MockRPCServerMockRecorder is the mock recorder for MockRPCServer.
type MockRPCServerMockRecorder struct {
	mock *MockRPCServer
}

// NewMockRPCServer creates a new mock instance.
func NewMockRPCServer(ctrl *gomock.Controller) *MockRPCServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCServer) EXPECT() *MockRPCServerMockRecorder {
	_ = "STUB: not implemented"

	// AfterInit mocks base method.
	return nil
}

func (m *MockRPCServer) AfterInit() { _ = "STUB: not implemented"; return }

// AfterInit indicates an expected call of AfterInit.
func (mr *MockRPCServerMockRecorder) AfterInit() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BeforeShutdown mocks base method.
func (m *MockRPCServer) BeforeShutdown() { _ = "STUB: not implemented"; return }

// BeforeShutdown indicates an expected call of BeforeShutdown.
func (mr *MockRPCServerMockRecorder) BeforeShutdown() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockRPCServer) Init() error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockRPCServerMockRecorder) Init() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SetPitayaServer mocks base method.
func (m *MockRPCServer) SetPitayaServer(arg0 protos.PitayaServer) {
	_ = "STUB: not implemented"
	return
}

// SetPitayaServer indicates an expected call of SetPitayaServer.
func (mr *MockRPCServerMockRecorder) SetPitayaServer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown mocks base method.
func (m *MockRPCServer) Shutdown() error { _ = "STUB: not implemented"; return nil }

// Shutdown indicates an expected call of Shutdown.
func (mr *MockRPCServerMockRecorder) Shutdown() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockRPCClient is a mock of RPCClient interface.
type MockRPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockRPCClientMockRecorder
}

// MockRPCClientMockRecorder is the mock recorder for MockRPCClient.
type MockRPCClientMockRecorder struct {
	mock *MockRPCClient
}

// NewMockRPCClient creates a new mock instance.
func NewMockRPCClient(ctrl *gomock.Controller) *MockRPCClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCClient) EXPECT() *MockRPCClientMockRecorder {
	_ = "STUB: not implemented"

	// AfterInit mocks base method.
	return nil
}

func (m *MockRPCClient) AfterInit() { _ = "STUB: not implemented"; return }

// AfterInit indicates an expected call of AfterInit.
func (mr *MockRPCClientMockRecorder) AfterInit() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BeforeShutdown mocks base method.
func (m *MockRPCClient) BeforeShutdown() { _ = "STUB: not implemented"; return }

// BeforeShutdown indicates an expected call of BeforeShutdown.
func (mr *MockRPCClientMockRecorder) BeforeShutdown() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BroadcastSessionBind mocks base method.
func (m *MockRPCClient) BroadcastSessionBind(uid string) error {
	_ = "STUB: not implemented"
	return nil
}

// BroadcastSessionBind indicates an expected call of BroadcastSessionBind.
func (mr *MockRPCClientMockRecorder) BroadcastSessionBind(uid interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Call mocks base method.
func (m *MockRPCClient) Call(ctx context.Context, rpcType protos.RPCType, route *route.Route, session session.Session, msg *message.Message, server *cluster.Server) (*protos.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Call indicates an expected call of Call.
func (mr *MockRPCClientMockRecorder) Call(ctx, rpcType, route, session, msg, server interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockRPCClient) Init() error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockRPCClientMockRecorder) Init() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Send mocks base method.
func (m *MockRPCClient) Send(route string, data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockRPCClientMockRecorder) Send(route, data interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendKick mocks base method.
func (m *MockRPCClient) SendKick(userID, serverType string, kick *protos.KickMsg) error {
	_ = "STUB: not implemented"
	return nil
}

// SendKick indicates an expected call of SendKick.
func (mr *MockRPCClientMockRecorder) SendKick(userID, serverType, kick interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendPush mocks base method.
func (m *MockRPCClient) SendPush(userID string, frontendSv *cluster.Server, push *protos.Push) error {
	_ = "STUB: not implemented"
	return nil
}

// SendPush indicates an expected call of SendPush.
func (mr *MockRPCClientMockRecorder) SendPush(userID, frontendSv, push interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown mocks base method.
func (m *MockRPCClient) Shutdown() error { _ = "STUB: not implemented"; return nil }

// Shutdown indicates an expected call of Shutdown.
func (mr *MockRPCClientMockRecorder) Shutdown() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockSDListener is a mock of SDListener interface.
type MockSDListener struct {
	ctrl     *gomock.Controller
	recorder *MockSDListenerMockRecorder
}

// MockSDListenerMockRecorder is the mock recorder for MockSDListener.
type MockSDListenerMockRecorder struct {
	mock *MockSDListener
}

// NewMockSDListener creates a new mock instance.
func NewMockSDListener(ctrl *gomock.Controller) *MockSDListener {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSDListener) EXPECT() *MockSDListenerMockRecorder {
	_ = "STUB: not implemented"

	// AddServer mocks base method.
	return nil
}

func (m *MockSDListener) AddServer(arg0 *cluster.Server) { _ = "STUB: not implemented"; return }

// AddServer indicates an expected call of AddServer.
func (mr *MockSDListenerMockRecorder) AddServer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveServer mocks base method.
func (m *MockSDListener) RemoveServer(arg0 *cluster.Server) { _ = "STUB: not implemented"; return }

// RemoveServer indicates an expected call of RemoveServer.
func (mr *MockSDListenerMockRecorder) RemoveServer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockRemoteBindingListener is a mock of RemoteBindingListener interface.
type MockRemoteBindingListener struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteBindingListenerMockRecorder
}

// MockRemoteBindingListenerMockRecorder is the mock recorder for MockRemoteBindingListener.
type MockRemoteBindingListenerMockRecorder struct {
	mock *MockRemoteBindingListener
}

// NewMockRemoteBindingListener creates a new mock instance.
func NewMockRemoteBindingListener(ctrl *gomock.Controller) *MockRemoteBindingListener {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteBindingListener) EXPECT() *MockRemoteBindingListenerMockRecorder {
	_ = "STUB: not implemented"

	// OnUserBind mocks base method.
	return nil
}

func (m *MockRemoteBindingListener) OnUserBind(uid, fid string) { _ = "STUB: not implemented"; return }

// OnUserBind indicates an expected call of OnUserBind.
func (mr *MockRemoteBindingListenerMockRecorder) OnUserBind(uid, fid interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockInfoRetriever is a mock of InfoRetriever interface.
type MockInfoRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockInfoRetrieverMockRecorder
}

// MockInfoRetrieverMockRecorder is the mock recorder for MockInfoRetriever.
type MockInfoRetrieverMockRecorder struct {
	mock *MockInfoRetriever
}

// NewMockInfoRetriever creates a new mock instance.
func NewMockInfoRetriever(ctrl *gomock.Controller) *MockInfoRetriever {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfoRetriever) EXPECT() *MockInfoRetrieverMockRecorder {
	_ = "STUB: not implemented"

	// Region mocks base method.
	return nil
}

func (m *MockInfoRetriever) Region() string { _ = "STUB: not implemented"; return "" }

// Region indicates an expected call of Region.
func (mr *MockInfoRetrieverMockRecorder) Region() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
