// Code generated by MockGen. DO NOT EDIT.
// Source: cluster/service_discovery.go

// Package mock_cluster is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	cluster "github.com/topfreegames/pitaya/v3/pkg/cluster"
)

// MockServiceDiscovery is a mock of ServiceDiscovery interface.
type MockServiceDiscovery struct {
	ctrl     *gomock.Controller
	recorder *MockServiceDiscoveryMockRecorder
}

// MockServiceDiscoveryMockRecorder is the mock recorder for MockServiceDiscovery.
type MockServiceDiscoveryMockRecorder struct {
	mock *MockServiceDiscovery
}

// NewMockServiceDiscovery creates a new mock instance.
func NewMockServiceDiscovery(ctrl *gomock.Controller) *MockServiceDiscovery {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceDiscovery) EXPECT() *MockServiceDiscoveryMockRecorder {
	_ = "STUB: not implemented"

	// AddListener mocks base method.
	return nil
}

func (m *MockServiceDiscovery) AddListener(listener cluster.SDListener) {
	_ = "STUB: not implemented"
	return
}

// AddListener indicates an expected call of AddListener.
func (mr *MockServiceDiscoveryMockRecorder) AddListener(listener interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AfterInit mocks base method.
func (m *MockServiceDiscovery) AfterInit() { _ = "STUB: not implemented"; return }

// AfterInit indicates an expected call of AfterInit.
func (mr *MockServiceDiscoveryMockRecorder) AfterInit() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BeforeShutdown mocks base method.
func (m *MockServiceDiscovery) BeforeShutdown() { _ = "STUB: not implemented"; return }

// BeforeShutdown indicates an expected call of BeforeShutdown.
func (mr *MockServiceDiscoveryMockRecorder) BeforeShutdown() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetServer mocks base method.
func (m *MockServiceDiscovery) GetServer(id string) (*cluster.Server, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetServer indicates an expected call of GetServer.
func (mr *MockServiceDiscoveryMockRecorder) GetServer(id interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetServers mocks base method.
func (m *MockServiceDiscovery) GetServers() []*cluster.Server {
	_ = "STUB: not implemented"
	return nil
}

// GetServers indicates an expected call of GetServers.
func (mr *MockServiceDiscoveryMockRecorder) GetServers() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetServersByType mocks base method.
func (m *MockServiceDiscovery) GetServersByType(serverType string) (map[string]*cluster.Server, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetServersByType indicates an expected call of GetServersByType.
func (mr *MockServiceDiscoveryMockRecorder) GetServersByType(serverType interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockServiceDiscovery) Init() error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockServiceDiscoveryMockRecorder) Init() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsConnected mocks base method.
func (m *MockServiceDiscovery) IsConnected(arg0 context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockServiceDiscoveryMockRecorder) IsConnected(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown mocks base method.
func (m *MockServiceDiscovery) Shutdown() error { _ = "STUB: not implemented"; return nil }

// Shutdown indicates an expected call of Shutdown.
func (mr *MockServiceDiscoveryMockRecorder) Shutdown() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SyncServers mocks base method.
func (m *MockServiceDiscovery) SyncServers(firstSync bool) error {
	_ = "STUB: not implemented"
	return nil
}

// SyncServers indicates an expected call of SyncServers.
func (mr *MockServiceDiscoveryMockRecorder) SyncServers(firstSync interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
