// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/topfreegames/pitaya/v3/pkg/agent (interfaces: Agent,AgentFactory)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	net "net"

	gomock "github.com/golang/mock/gomock"
	agent "github.com/topfreegames/pitaya/v3/pkg/agent"
	protos "github.com/topfreegames/pitaya/v3/pkg/protos"
	session "github.com/topfreegames/pitaya/v3/pkg/session"
)

// MockAgent is a mock of Agent interface.
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
}

// MockAgentMockRecorder is the mock recorder for MockAgent.
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance.
func NewMockAgent(ctrl *gomock.Controller) *MockAgent { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	_ = "STUB: not implemented"

	// AnswerWithError mocks base method.
	return nil
}

func (m *MockAgent) AnswerWithError(arg0 context.Context, arg1 uint, arg2 error) {
	_ = "STUB: not implemented"
	return
}

// AnswerWithError indicates an expected call of AnswerWithError.
func (mr *MockAgentMockRecorder) AnswerWithError(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Close mocks base method.
func (m *MockAgent) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockAgentMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetSession mocks base method.
func (m *MockAgent) GetSession() session.Session {
	_ = "STUB: not implemented"
	return *new(session.Session)
}

// GetSession indicates an expected call of GetSession.
func (mr *MockAgentMockRecorder) GetSession() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetStatus mocks base method.
func (m *MockAgent) GetStatus() int32 { _ = "STUB: not implemented"; return 0 }

// GetStatus indicates an expected call of GetStatus.
func (mr *MockAgentMockRecorder) GetStatus() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Handle mocks base method.
func (m *MockAgent) Handle() { _ = "STUB: not implemented"; return }

// Handle indicates an expected call of Handle.
func (mr *MockAgentMockRecorder) Handle() *gomock.Call { _ = "STUB: not implemented"; return nil }

// IPVersion mocks base method.
func (m *MockAgent) IPVersion() string { _ = "STUB: not implemented"; return "" }

// IPVersion indicates an expected call of IPVersion.
func (mr *MockAgentMockRecorder) IPVersion() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Kick mocks base method.
func (m *MockAgent) Kick(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Kick indicates an expected call of Kick.
func (mr *MockAgentMockRecorder) Kick(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Push mocks base method.
func (m *MockAgent) Push(arg0 string, arg1 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// Push indicates an expected call of Push.
func (mr *MockAgentMockRecorder) Push(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoteAddr mocks base method.
func (m *MockAgent) RemoteAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// RemoteAddr indicates an expected call of RemoteAddr.
func (mr *MockAgentMockRecorder) RemoteAddr() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ResponseMID mocks base method.
func (m *MockAgent) ResponseMID(arg0 context.Context, arg1 uint, arg2 interface{}, arg3 ...bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ResponseMID indicates an expected call of ResponseMID.
func (mr *MockAgentMockRecorder) ResponseMID(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHandshakeErrorResponse mocks base method.
func (m *MockAgent) SendHandshakeErrorResponse() error { _ = "STUB: not implemented"; return nil }

// SendHandshakeErrorResponse indicates an expected call of SendHandshakeErrorResponse.
func (mr *MockAgentMockRecorder) SendHandshakeErrorResponse() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHandshakeResponse mocks base method.
func (m *MockAgent) SendHandshakeResponse() error { _ = "STUB: not implemented"; return nil }

// SendHandshakeResponse indicates an expected call of SendHandshakeResponse.
func (mr *MockAgentMockRecorder) SendHandshakeResponse() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendRequest mocks base method.
func (m *MockAgent) SendRequest(arg0 context.Context, arg1, arg2 string, arg3 interface{}) (*protos.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SendRequest indicates an expected call of SendRequest.
func (mr *MockAgentMockRecorder) SendRequest(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetLastAt mocks base method.
func (m *MockAgent) SetLastAt() { _ = "STUB: not implemented"; return }

// SetLastAt indicates an expected call of SetLastAt.
func (mr *MockAgentMockRecorder) SetLastAt() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SetStatus mocks base method.
func (m *MockAgent) SetStatus(arg0 int32) { _ = "STUB: not implemented"; return }

// SetStatus indicates an expected call of SetStatus.
func (mr *MockAgentMockRecorder) SetStatus(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// String mocks base method.
func (m *MockAgent) String() string { _ = "STUB: not implemented"; return "" }

// String indicates an expected call of String.
func (mr *MockAgentMockRecorder) String() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockAgentFactory is a mock of AgentFactory interface.
type MockAgentFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAgentFactoryMockRecorder
}

// MockAgentFactoryMockRecorder is the mock recorder for MockAgentFactory.
type MockAgentFactoryMockRecorder struct {
	mock *MockAgentFactory
}

// NewMockAgentFactory creates a new mock instance.
func NewMockAgentFactory(ctrl *gomock.Controller) *MockAgentFactory {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentFactory) EXPECT() *MockAgentFactoryMockRecorder {
	_ = "STUB: not implemented"

	// CreateAgent mocks base method.
	return nil
}

func (m *MockAgentFactory) CreateAgent(arg0 net.Conn) agent.Agent {
	_ = "STUB: not implemented"
	return *new(agent.Agent)
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockAgentFactoryMockRecorder) CreateAgent(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
