// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protodescriptor.proto

package protos

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Descriptor proto used to retrieve zipped proto descriptors remotely
type ProtoDescriptor struct {
	Desc                 []byte   `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoDescriptor) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProtoDescriptor) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProtoDescriptor) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProtoDescriptor) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProtoDescriptor) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProtoDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (dst *ProtoDescriptor) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProtoDescriptor) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProtoDescriptor) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProtoDescriptor proto.InternalMessageInfo

func (m *ProtoDescriptor) GetDesc() []byte { _ = "STUB: not implemented"; return nil }

type ProtoName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoName) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProtoName) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProtoName) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProtoName) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProtoName) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProtoName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (dst *ProtoName) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProtoName) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProtoName) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProtoName proto.InternalMessageInfo

func (m *ProtoName) GetName() string { _ = "STUB: not implemented"; return "" }

type ProtoDescriptors struct {
	Desc                 [][]byte `protobuf:"bytes,1,rep,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoDescriptors) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProtoDescriptors) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProtoDescriptors) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProtoDescriptors) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProtoDescriptors) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProtoDescriptors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (dst *ProtoDescriptors) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProtoDescriptors) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProtoDescriptors) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProtoDescriptors proto.InternalMessageInfo

func (m *ProtoDescriptors) GetDesc() [][]byte { _ = "STUB: not implemented"; return nil }

type ProtoNames struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoNames) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ProtoNames) String() string            { _ = "STUB: not implemented"; return "" }
func (*ProtoNames) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ProtoNames) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ProtoNames) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ProtoNames) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (dst *ProtoNames) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ProtoNames) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ProtoNames) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ProtoNames proto.InternalMessageInfo

func (m *ProtoNames) GetName() []string { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*ProtoDescriptor)(nil), "protos.ProtoDescriptor")
	proto.RegisterType((*ProtoName)(nil), "protos.ProtoName")
	proto.RegisterType((*ProtoDescriptors)(nil), "protos.ProtoDescriptors")
	proto.RegisterType((*ProtoNames)(nil), "protos.ProtoNames")
}

func init() {
	proto.RegisterFile("protodescriptor.proto", fileDescriptor_protodescriptor_d1dc0afa30ee5672)
}

var fileDescriptor_protodescriptor_d1dc0afa30ee5672 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x49, 0x2d, 0x4e, 0x2e, 0xca, 0x2c, 0x28, 0xc9, 0x2f, 0xd2, 0x03, 0xf3, 0x85, 0xd8,
	0xc0, 0x54, 0xb1, 0x92, 0x2a, 0x17, 0x7f, 0x00, 0x88, 0xe5, 0x02, 0x57, 0x20, 0x24, 0xc4, 0xc5,
	0x02, 0x52, 0x2e, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x2b, 0xc9, 0x73, 0x71, 0x82,
	0x95, 0xf9, 0x25, 0xe6, 0xa6, 0x82, 0x14, 0xe4, 0x25, 0xe6, 0xa6, 0x82, 0x15, 0x70, 0x06, 0x81,
	0xd9, 0x4a, 0x6a, 0x5c, 0x02, 0x68, 0xe6, 0x14, 0x23, 0x19, 0xc4, 0x0c, 0x37, 0x48, 0x81, 0x8b,
	0x0b, 0x6e, 0x50, 0x31, 0x92, 0x49, 0xcc, 0x30, 0x93, 0x92, 0x20, 0x2e, 0x33, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x91, 0xb4, 0x22, 0x97, 0xb9, 0x00, 0x00, 0x00,
}
