// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: examples/demo/protos/cluster.proto

package protos

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RPCMsg message to be sent using rpc
type RPCMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *RPCMsg) Reset() { _ = "STUB: not implemented"; return }

func (x *RPCMsg) String() string { _ = "STUB: not implemented"; return "" }

func (*RPCMsg) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RPCMsg) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RPCMsg.ProtoReflect.Descriptor instead.
func (*RPCMsg) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *RPCMsg) GetMsg() string { _ = "STUB: not implemented"; return "" }

// RPCRes is the rpc response
type RPCRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *RPCRes) Reset() { _ = "STUB: not implemented"; return }

func (x *RPCRes) String() string { _ = "STUB: not implemented"; return "" }

func (*RPCRes) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RPCRes) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RPCRes.ProtoReflect.Descriptor instead.
func (*RPCRes) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *RPCRes) GetMsg() string { _ = "STUB: not implemented"; return "" }

// UserMessage represents a message that user sent
type UserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *UserMessage) Reset() { _ = "STUB: not implemented"; return }

func (x *UserMessage) String() string { _ = "STUB: not implemented"; return "" }

func (*UserMessage) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *UserMessage) GetName() string { _ = "STUB: not implemented"; return "" }

func (x *UserMessage) GetContent() string { _ = "STUB: not implemented"; return "" }

// Stats exports the room status
type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutboundBytes int64 `protobuf:"varint,1,opt,name=outbound_bytes,json=outboundBytes,proto3" json:"outbound_bytes,omitempty"`
	InboundBytes  int64 `protobuf:"varint,2,opt,name=inbound_bytes,json=inboundBytes,proto3" json:"inbound_bytes,omitempty"`
}

func (x *Stats) Reset() { _ = "STUB: not implemented"; return }

func (x *Stats) String() string { _ = "STUB: not implemented"; return "" }

func (*Stats) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Stats) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Stats) GetOutboundBytes() int64 { _ = "STUB: not implemented"; return 0 }

func (x *Stats) GetInboundBytes() int64 { _ = "STUB: not implemented"; return 0 }

// SendRPCMsg represents a rpc message
type SendRPCMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Route    string `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Msg      string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendRPCMsg) Reset() { _ = "STUB: not implemented"; return }

func (x *SendRPCMsg) String() string { _ = "STUB: not implemented"; return "" }

func (*SendRPCMsg) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *SendRPCMsg) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use SendRPCMsg.ProtoReflect.Descriptor instead.
func (*SendRPCMsg) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *SendRPCMsg) GetServerId() string { _ = "STUB: not implemented"; return "" }

func (x *SendRPCMsg) GetRoute() string { _ = "STUB: not implemented"; return "" }

func (x *SendRPCMsg) GetMsg() string { _ = "STUB: not implemented"; return "" }

// NewUser message will be received when new user join room
type NewUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *NewUser) Reset() { _ = "STUB: not implemented"; return }

func (x *NewUser) String() string { _ = "STUB: not implemented"; return "" }

func (*NewUser) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *NewUser) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use NewUser.ProtoReflect.Descriptor instead.
func (*NewUser) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *NewUser) GetContent() string { _ = "STUB: not implemented"; return "" }

// AllMembers contains all members uid
type AllMembers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []string `protobuf:"bytes,1,rep,name=Members,proto3" json:"Members,omitempty"`
}

func (x *AllMembers) Reset() { _ = "STUB: not implemented"; return }

func (x *AllMembers) String() string { _ = "STUB: not implemented"; return "" }

func (*AllMembers) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *AllMembers) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use AllMembers.ProtoReflect.Descriptor instead.
func (*AllMembers) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *AllMembers) GetMembers() []string { _ = "STUB: not implemented"; return nil }

// JoinResponse represents the result of joining room
type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *JoinResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *JoinResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*JoinResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *JoinResponse) GetCode() int64 { _ = "STUB: not implemented"; return 0 }

func (x *JoinResponse) GetResult() string { _ = "STUB: not implemented"; return "" }

// Response struct
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Response) Reset() { _ = "STUB: not implemented"; return }

func (x *Response) String() string { _ = "STUB: not implemented"; return "" }

func (*Response) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Response) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Response) GetCode() int32 { _ = "STUB: not implemented"; return 0 }

func (x *Response) GetMsg() string { _ = "STUB: not implemented"; return "" }

var File_examples_demo_protos_cluster_proto protoreflect.FileDescriptor

var file_examples_demo_protos_cluster_proto_rawDesc = []byte{
	0x0a, 0x22, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x22, 0x1a, 0x0a, 0x06, 0x52, 0x50, 0x43, 0x4d, 0x73, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67,
	0x22, 0x1a, 0x0a, 0x06, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x3b, 0x0a, 0x0b,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x53, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6f, 0x75, 0x74, 0x62,
	0x6f, 0x75, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x62,
	0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x51,
	0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x50, 0x43, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x23, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x3a,
	0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x30, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x16, 0x5a, 0x14,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_examples_demo_protos_cluster_proto_rawDescOnce sync.Once
	file_examples_demo_protos_cluster_proto_rawDescData = file_examples_demo_protos_cluster_proto_rawDesc
)

func file_examples_demo_protos_cluster_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_examples_demo_protos_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_examples_demo_protos_cluster_proto_goTypes = []interface{}{
	(*RPCMsg)(nil),       // 0: cluster_protos.RPCMsg
	(*RPCRes)(nil),       // 1: cluster_protos.RPCRes
	(*UserMessage)(nil),  // 2: cluster_protos.UserMessage
	(*Stats)(nil),        // 3: cluster_protos.Stats
	(*SendRPCMsg)(nil),   // 4: cluster_protos.SendRPCMsg
	(*NewUser)(nil),      // 5: cluster_protos.NewUser
	(*AllMembers)(nil),   // 6: cluster_protos.AllMembers
	(*JoinResponse)(nil), // 7: cluster_protos.JoinResponse
	(*Response)(nil),     // 8: cluster_protos.Response
}
var file_examples_demo_protos_cluster_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                         { file_examples_demo_protos_cluster_proto_init() }
func file_examples_demo_protos_cluster_proto_init() { _ = "STUB: not implemented"; return }
