// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/topfreegames/pitaya/v3/pkg/worker (interfaces: RPCJob)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
)

// MockRPCJob is a mock of RPCJob interface.
type MockRPCJob struct {
	ctrl     *gomock.Controller
	recorder *MockRPCJobMockRecorder
}

// MockRPCJobMockRecorder is the mock recorder for MockRPCJob.
type MockRPCJobMockRecorder struct {
	mock *MockRPCJob
}

// NewMockRPCJob creates a new mock instance.
func NewMockRPCJob(ctrl *gomock.Controller) *MockRPCJob { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCJob) EXPECT() *MockRPCJobMockRecorder {
	_ = "STUB: not implemented"

	// GetArgReply mocks base method.
	return nil
}

func (m *MockRPCJob) GetArgReply(arg0 string) (protoiface.MessageV1, protoiface.MessageV1, error) {
	_ = "STUB: not implemented"
	return *new(protoiface.MessageV1), *new(protoiface.MessageV1), nil
}

// GetArgReply indicates an expected call of GetArgReply.
func (mr *MockRPCJobMockRecorder) GetArgReply(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RPC mocks base method.
func (m *MockRPCJob) RPC(arg0 context.Context, arg1, arg2 string, arg3, arg4 protoiface.MessageV1) error {
	_ = "STUB: not implemented"
	return nil
}

// RPC indicates an expected call of RPC.
func (mr *MockRPCJobMockRecorder) RPC(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ServerDiscovery mocks base method.
func (m *MockRPCJob) ServerDiscovery(arg0 string, arg1 map[string]interface{}) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// ServerDiscovery indicates an expected call of ServerDiscovery.
func (mr *MockRPCJobMockRecorder) ServerDiscovery(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
