// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package protos

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Response) String() string            { _ = "STUB: not implemented"; return "" }
func (*Response) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Response) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Response) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (dst *Response) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Response) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Response) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 { _ = "STUB: not implemented"; return 0 }

func (m *Response) GetMsg() string { _ = "STUB: not implemented"; return "" }

func init() {
	proto.RegisterType((*Response)(nil), "protos.Response")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_response_7319a4323854ca68) }

var fileDescriptor_response_7319a4323854ca68 = []byte{
	// 88 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a,
	0x06, 0x5c, 0x1c, 0x41, 0x50, 0x19, 0x21, 0x21, 0x2e, 0x96, 0xe4, 0xfc, 0x94, 0x54, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0x39, 0xb7, 0x38, 0x5d, 0x82, 0x49,
	0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x4c, 0x82, 0xe8, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x46, 0x18, 0xa3, 0x40, 0x52, 0x00, 0x00, 0x00,
}
