// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockModule is a mock of Module interface
type MockModule struct {
	ctrl     *gomock.Controller
	recorder *MockModuleMockRecorder
}

// MockModuleMockRecorder is the mock recorder for MockModule
type MockModuleMockRecorder struct {
	mock *MockModule
}

// NewMockModule creates a new mock instance
func NewMockModule(ctrl *gomock.Controller) *MockModule { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockModule) EXPECT() *MockModuleMockRecorder {
	_ = "STUB: not implemented"

	// Init mocks base method
	return nil
}

func (m *MockModule) Init() error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init
func (mr *MockModuleMockRecorder) Init() *gomock.Call { _ = "STUB: not implemented"; return nil }

// AfterInit mocks base method
func (m *MockModule) AfterInit() { _ = "STUB: not implemented"; return }

// AfterInit indicates an expected call of AfterInit
func (mr *MockModuleMockRecorder) AfterInit() *gomock.Call { _ = "STUB: not implemented"; return nil }

// BeforeShutdown mocks base method
func (m *MockModule) BeforeShutdown() { _ = "STUB: not implemented"; return }

// BeforeShutdown indicates an expected call of BeforeShutdown
func (mr *MockModuleMockRecorder) BeforeShutdown() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown mocks base method
func (m *MockModule) Shutdown() error { _ = "STUB: not implemented"; return nil }

// Shutdown indicates an expected call of Shutdown
func (mr *MockModuleMockRecorder) Shutdown() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockBindingStorage is a mock of BindingStorage interface
type MockBindingStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBindingStorageMockRecorder
}

// MockBindingStorageMockRecorder is the mock recorder for MockBindingStorage
type MockBindingStorageMockRecorder struct {
	mock *MockBindingStorage
}

// NewMockBindingStorage creates a new mock instance
func NewMockBindingStorage(ctrl *gomock.Controller) *MockBindingStorage {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBindingStorage) EXPECT() *MockBindingStorageMockRecorder {
	_ = "STUB: not implemented"

	// GetUserFrontendID mocks base method
	return nil
}

func (m *MockBindingStorage) GetUserFrontendID(uid, frontendType string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetUserFrontendID indicates an expected call of GetUserFrontendID
func (mr *MockBindingStorageMockRecorder) GetUserFrontendID(uid, frontendType interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PutBinding mocks base method
func (m *MockBindingStorage) PutBinding(uid string) error { _ = "STUB: not implemented"; return nil }

// PutBinding indicates an expected call of PutBinding
func (mr *MockBindingStorageMockRecorder) PutBinding(uid interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
