// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/topfreegames/pitaya/v3/pkg/acceptor (interfaces: PlayerConn,Acceptor)

// Package mocks is a generated GoMock package.
package mocks

import (
	net "net"
	time "time"

	gomock "github.com/golang/mock/gomock"
	acceptor "github.com/topfreegames/pitaya/v3/pkg/acceptor"
)

// MockPlayerConn is a mock of PlayerConn interface.
type MockPlayerConn struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerConnMockRecorder
}

// MockPlayerConnMockRecorder is the mock recorder for MockPlayerConn.
type MockPlayerConnMockRecorder struct {
	mock *MockPlayerConn
}

// NewMockPlayerConn creates a new mock instance.
func NewMockPlayerConn(ctrl *gomock.Controller) *MockPlayerConn {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerConn) EXPECT() *MockPlayerConnMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockPlayerConn) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockPlayerConnMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetNextMessage mocks base method.
func (m *MockPlayerConn) GetNextMessage() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNextMessage indicates an expected call of GetNextMessage.
func (mr *MockPlayerConnMockRecorder) GetNextMessage() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LocalAddr mocks base method.
func (m *MockPlayerConn) LocalAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// LocalAddr indicates an expected call of LocalAddr.
func (mr *MockPlayerConnMockRecorder) LocalAddr() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Read mocks base method.
func (m *MockPlayerConn) Read(arg0 []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// Read indicates an expected call of Read.
func (mr *MockPlayerConnMockRecorder) Read(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoteAddr mocks base method.
func (m *MockPlayerConn) RemoteAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// RemoteAddr indicates an expected call of RemoteAddr.
func (mr *MockPlayerConnMockRecorder) RemoteAddr() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDeadline mocks base method.
func (m *MockPlayerConn) SetDeadline(arg0 time.Time) error { _ = "STUB: not implemented"; return nil }

// SetDeadline indicates an expected call of SetDeadline.
func (mr *MockPlayerConnMockRecorder) SetDeadline(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetReadDeadline mocks base method.
func (m *MockPlayerConn) SetReadDeadline(arg0 time.Time) error {
	_ = "STUB: not implemented"
	return nil
}

// SetReadDeadline indicates an expected call of SetReadDeadline.
func (mr *MockPlayerConnMockRecorder) SetReadDeadline(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetWriteDeadline mocks base method.
func (m *MockPlayerConn) SetWriteDeadline(arg0 time.Time) error {
	_ = "STUB: not implemented"
	return nil
}

// SetWriteDeadline indicates an expected call of SetWriteDeadline.
func (mr *MockPlayerConnMockRecorder) SetWriteDeadline(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Write mocks base method.
func (m *MockPlayerConn) Write(arg0 []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// Write indicates an expected call of Write.
func (mr *MockPlayerConnMockRecorder) Write(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAcceptor is a mock of Acceptor interface.
type MockAcceptor struct {
	ctrl     *gomock.Controller
	recorder *MockAcceptorMockRecorder
}

// MockAcceptorMockRecorder is the mock recorder for MockAcceptor.
type MockAcceptorMockRecorder struct {
	mock *MockAcceptor
}

// NewMockAcceptor creates a new mock instance.
func NewMockAcceptor(ctrl *gomock.Controller) *MockAcceptor { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcceptor) EXPECT() *MockAcceptorMockRecorder {
	_ = "STUB: not implemented"

	// EnableProxyProtocol mocks base method.
	return nil
}

func (m *MockAcceptor) EnableProxyProtocol() { _ = "STUB: not implemented"; return }

// EnableProxyProtocol indicates an expected call of EnableProxyProtocol.
func (mr *MockAcceptorMockRecorder) EnableProxyProtocol() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAddr mocks base method.
func (m *MockAcceptor) GetAddr() string { _ = "STUB: not implemented"; return "" }

// GetAddr indicates an expected call of GetAddr.
func (mr *MockAcceptorMockRecorder) GetAddr() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetConfiguredAddress mocks base method.
func (m *MockAcceptor) GetConfiguredAddress() string { _ = "STUB: not implemented"; return "" }

// GetConfiguredAddress indicates an expected call of GetConfiguredAddress.
func (mr *MockAcceptorMockRecorder) GetConfiguredAddress() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetConnChan mocks base method.
func (m *MockAcceptor) GetConnChan() chan acceptor.PlayerConn {
	_ = "STUB: not implemented"
	return nil
}

// GetConnChan indicates an expected call of GetConnChan.
func (mr *MockAcceptorMockRecorder) GetConnChan() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsRunning mocks base method.
func (m *MockAcceptor) IsRunning() bool { _ = "STUB: not implemented"; return false }

// IsRunning indicates an expected call of IsRunning.
func (mr *MockAcceptorMockRecorder) IsRunning() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ListenAndServe mocks base method.
func (m *MockAcceptor) ListenAndServe() { _ = "STUB: not implemented"; return }

// ListenAndServe indicates an expected call of ListenAndServe.
func (mr *MockAcceptorMockRecorder) ListenAndServe() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockAcceptor) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockAcceptorMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }
