// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/topfreegames/pitaya/v3/pkg (interfaces: Pitaya)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	time "time"

	gomock "github.com/golang/mock/gomock"
	cluster "github.com/topfreegames/pitaya/v3/pkg/cluster"
	component "github.com/topfreegames/pitaya/v3/pkg/component"
	config "github.com/topfreegames/pitaya/v3/pkg/config"
	interfaces "github.com/topfreegames/pitaya/v3/pkg/interfaces"
	metrics "github.com/topfreegames/pitaya/v3/pkg/metrics"
	router "github.com/topfreegames/pitaya/v3/pkg/router"
	session "github.com/topfreegames/pitaya/v3/pkg/session"
	worker "github.com/topfreegames/pitaya/v3/pkg/worker"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
)

// MockPitaya is a mock of Pitaya interface.
type MockPitaya struct {
	ctrl     *gomock.Controller
	recorder *MockPitayaMockRecorder
}

// MockPitayaMockRecorder is the mock recorder for MockPitaya.
type MockPitayaMockRecorder struct {
	mock *MockPitaya
}

// NewMockPitaya creates a new mock instance.
func NewMockPitaya(ctrl *gomock.Controller) *MockPitaya { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPitaya) EXPECT() *MockPitayaMockRecorder {
	_ = "STUB: not implemented"

	// AddRoute mocks base method.
	return nil
}

func (m *MockPitaya) AddRoute(arg0 string, arg1 router.RoutingFunc) error {
	_ = "STUB: not implemented"
	return nil
}

// AddRoute indicates an expected call of AddRoute.
func (mr *MockPitayaMockRecorder) AddRoute(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Documentation mocks base method.
func (m *MockPitaya) Documentation(arg0 bool) (map[string]interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Documentation indicates an expected call of Documentation.
func (mr *MockPitayaMockRecorder) Documentation(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDieChan mocks base method.
func (m *MockPitaya) GetDieChan() chan bool { _ = "STUB: not implemented"; return nil }

// GetDieChan indicates an expected call of GetDieChan.
func (mr *MockPitayaMockRecorder) GetDieChan() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetMetricsReporters mocks base method.
func (m *MockPitaya) GetMetricsReporters() []metrics.Reporter {
	_ = "STUB: not implemented"
	return nil
}

// GetMetricsReporters indicates an expected call of GetMetricsReporters.
func (mr *MockPitayaMockRecorder) GetMetricsReporters() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetModule mocks base method.
func (m *MockPitaya) GetModule(arg0 string) (interfaces.Module, error) {
	_ = "STUB: not implemented"
	return *new(interfaces.Module), nil
}

// GetModule indicates an expected call of GetModule.
func (mr *MockPitayaMockRecorder) GetModule(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNumberOfConnectedClients mocks base method.
func (m *MockPitaya) GetNumberOfConnectedClients() int64 { _ = "STUB: not implemented"; return 0 }

// GetNumberOfConnectedClients indicates an expected call of GetNumberOfConnectedClients.
func (mr *MockPitayaMockRecorder) GetNumberOfConnectedClients() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetServer mocks base method.
func (m *MockPitaya) GetServer() *cluster.Server { _ = "STUB: not implemented"; return nil }

// GetServer indicates an expected call of GetServer.
func (mr *MockPitayaMockRecorder) GetServer() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetServerByID mocks base method.
func (m *MockPitaya) GetServerByID(arg0 string) (*cluster.Server, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetServerByID indicates an expected call of GetServerByID.
func (mr *MockPitayaMockRecorder) GetServerByID(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetServerID mocks base method.
func (m *MockPitaya) GetServerID() string { _ = "STUB: not implemented"; return "" }

// GetServerID indicates an expected call of GetServerID.
func (mr *MockPitayaMockRecorder) GetServerID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetServers mocks base method.
func (m *MockPitaya) GetServers() []*cluster.Server { _ = "STUB: not implemented"; return nil }

// GetServers indicates an expected call of GetServers.
func (mr *MockPitayaMockRecorder) GetServers() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetServersByType mocks base method.
func (m *MockPitaya) GetServersByType(arg0 string) (map[string]*cluster.Server, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetServersByType indicates an expected call of GetServersByType.
func (mr *MockPitayaMockRecorder) GetServersByType(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSessionFromCtx mocks base method.
func (m *MockPitaya) GetSessionFromCtx(arg0 context.Context) session.Session {
	_ = "STUB: not implemented"
	return *new(session.Session)
}

// GetSessionFromCtx indicates an expected call of GetSessionFromCtx.
func (mr *MockPitayaMockRecorder) GetSessionFromCtx(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupAddMember mocks base method.
func (m *MockPitaya) GroupAddMember(arg0 context.Context, arg1, arg2 string) error {
	_ = "STUB: not implemented"
	return nil
}

// GroupAddMember indicates an expected call of GroupAddMember.
func (mr *MockPitayaMockRecorder) GroupAddMember(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupBroadcast mocks base method.
func (m *MockPitaya) GroupBroadcast(arg0 context.Context, arg1, arg2, arg3 string, arg4 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// GroupBroadcast indicates an expected call of GroupBroadcast.
func (mr *MockPitayaMockRecorder) GroupBroadcast(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupContainsMember mocks base method.
func (m *MockPitaya) GroupContainsMember(arg0 context.Context, arg1, arg2 string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// GroupContainsMember indicates an expected call of GroupContainsMember.
func (mr *MockPitayaMockRecorder) GroupContainsMember(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupCountMembers mocks base method.
func (m *MockPitaya) GroupCountMembers(arg0 context.Context, arg1 string) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// GroupCountMembers indicates an expected call of GroupCountMembers.
func (mr *MockPitayaMockRecorder) GroupCountMembers(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupCreate mocks base method.
func (m *MockPitaya) GroupCreate(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// GroupCreate indicates an expected call of GroupCreate.
func (mr *MockPitayaMockRecorder) GroupCreate(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupCreateWithTTL mocks base method.
func (m *MockPitaya) GroupCreateWithTTL(arg0 context.Context, arg1 string, arg2 time.Duration) error {
	_ = "STUB: not implemented"
	return nil
}

// GroupCreateWithTTL indicates an expected call of GroupCreateWithTTL.
func (mr *MockPitayaMockRecorder) GroupCreateWithTTL(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupDelete mocks base method.
func (m *MockPitaya) GroupDelete(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// GroupDelete indicates an expected call of GroupDelete.
func (mr *MockPitayaMockRecorder) GroupDelete(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupMembers mocks base method.
func (m *MockPitaya) GroupMembers(arg0 context.Context, arg1 string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GroupMembers indicates an expected call of GroupMembers.
func (mr *MockPitayaMockRecorder) GroupMembers(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupRemoveAll mocks base method.
func (m *MockPitaya) GroupRemoveAll(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// GroupRemoveAll indicates an expected call of GroupRemoveAll.
func (mr *MockPitayaMockRecorder) GroupRemoveAll(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupRemoveMember mocks base method.
func (m *MockPitaya) GroupRemoveMember(arg0 context.Context, arg1, arg2 string) error {
	_ = "STUB: not implemented"
	return nil
}

// GroupRemoveMember indicates an expected call of GroupRemoveMember.
func (mr *MockPitayaMockRecorder) GroupRemoveMember(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupRenewTTL mocks base method.
func (m *MockPitaya) GroupRenewTTL(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// GroupRenewTTL indicates an expected call of GroupRenewTTL.
func (mr *MockPitayaMockRecorder) GroupRenewTTL(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsReady mocks base method.
func (m *MockPitaya) IsReady(arg0 context.Context) bool { _ = "STUB: not implemented"; return false }

// IsReady indicates an expected call of IsReady.
func (mr *MockPitayaMockRecorder) IsReady(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsRunning mocks base method.
func (m *MockPitaya) IsRunning() bool { _ = "STUB: not implemented"; return false }

// IsRunning indicates an expected call of IsRunning.
func (mr *MockPitayaMockRecorder) IsRunning() *gomock.Call { _ = "STUB: not implemented"; return nil }

// RPC mocks base method.
func (m *MockPitaya) RPC(arg0 context.Context, arg1 string, arg2, arg3 protoiface.MessageV1) error {
	_ = "STUB: not implemented"
	return nil
}

// RPC indicates an expected call of RPC.
func (mr *MockPitayaMockRecorder) RPC(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RPCTo mocks base method.
func (m *MockPitaya) RPCTo(arg0 context.Context, arg1, arg2 string, arg3, arg4 protoiface.MessageV1) error {
	_ = "STUB: not implemented"
	return nil
}

// RPCTo indicates an expected call of RPCTo.
func (mr *MockPitayaMockRecorder) RPCTo(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Register mocks base method.
func (m *MockPitaya) Register(arg0 component.Component, arg1 ...component.Option) {
	_ = "STUB: not implemented"
	return
}

// Register indicates an expected call of Register.
func (mr *MockPitayaMockRecorder) Register(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterModule mocks base method.
func (m *MockPitaya) RegisterModule(arg0 interfaces.Module, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterModule indicates an expected call of RegisterModule.
func (mr *MockPitayaMockRecorder) RegisterModule(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterModuleAfter mocks base method.
func (m *MockPitaya) RegisterModuleAfter(arg0 interfaces.Module, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterModuleAfter indicates an expected call of RegisterModuleAfter.
func (mr *MockPitayaMockRecorder) RegisterModuleAfter(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterModuleBefore mocks base method.
func (m *MockPitaya) RegisterModuleBefore(arg0 interfaces.Module, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterModuleBefore indicates an expected call of RegisterModuleBefore.
func (mr *MockPitayaMockRecorder) RegisterModuleBefore(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterRPCJob mocks base method.
func (m *MockPitaya) RegisterRPCJob(arg0 worker.RPCJob) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterRPCJob indicates an expected call of RegisterRPCJob.
func (mr *MockPitayaMockRecorder) RegisterRPCJob(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterRemote mocks base method.
func (m *MockPitaya) RegisterRemote(arg0 component.Component, arg1 ...component.Option) {
	_ = "STUB: not implemented"
	return
}

// RegisterRemote indicates an expected call of RegisterRemote.
func (mr *MockPitayaMockRecorder) RegisterRemote(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReliableRPC mocks base method.
func (m *MockPitaya) ReliableRPC(arg0 string, arg1 map[string]interface{}, arg2, arg3 protoiface.MessageV1) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// ReliableRPC indicates an expected call of ReliableRPC.
func (mr *MockPitayaMockRecorder) ReliableRPC(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReliableRPCWithOptions mocks base method.
func (m *MockPitaya) ReliableRPCWithOptions(arg0 string, arg1 map[string]interface{}, arg2, arg3 protoiface.MessageV1, arg4 *config.EnqueueOpts) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// ReliableRPCWithOptions indicates an expected call of ReliableRPCWithOptions.
func (mr *MockPitayaMockRecorder) ReliableRPCWithOptions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendKickToUsers mocks base method.
func (m *MockPitaya) SendKickToUsers(arg0 []string, arg1 string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SendKickToUsers indicates an expected call of SendKickToUsers.
func (mr *MockPitayaMockRecorder) SendKickToUsers(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendPushToUsers mocks base method.
func (m *MockPitaya) SendPushToUsers(arg0 string, arg1 interface{}, arg2 []string, arg3 string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SendPushToUsers indicates an expected call of SendPushToUsers.
func (mr *MockPitayaMockRecorder) SendPushToUsers(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDebug mocks base method.
func (m *MockPitaya) SetDebug(arg0 bool) { _ = "STUB: not implemented"; return }

// SetDebug indicates an expected call of SetDebug.
func (mr *MockPitayaMockRecorder) SetDebug(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDictionary mocks base method.
func (m *MockPitaya) SetDictionary(arg0 map[string]uint16) error {
	_ = "STUB: not implemented"
	return nil
}

// SetDictionary indicates an expected call of SetDictionary.
func (mr *MockPitayaMockRecorder) SetDictionary(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeartbeatTime mocks base method.
func (m *MockPitaya) SetHeartbeatTime(arg0 time.Duration) { _ = "STUB: not implemented"; return }

// SetHeartbeatTime indicates an expected call of SetHeartbeatTime.
func (mr *MockPitayaMockRecorder) SetHeartbeatTime(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown mocks base method.
func (m *MockPitaya) Shutdown() { _ = "STUB: not implemented"; return }

// Shutdown indicates an expected call of Shutdown.
func (mr *MockPitayaMockRecorder) Shutdown() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Start mocks base method.
func (m *MockPitaya) Start() { _ = "STUB: not implemented"; return }

// Start indicates an expected call of Start.
func (mr *MockPitayaMockRecorder) Start() *gomock.Call { _ = "STUB: not implemented"; return nil }

// StartWorker mocks base method.
func (m *MockPitaya) StartWorker() { _ = "STUB: not implemented"; return }

// StartWorker indicates an expected call of StartWorker.
func (mr *MockPitayaMockRecorder) StartWorker() *gomock.Call { _ = "STUB: not implemented"; return nil }
