// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/topfreegames/pitaya/v3/pkg/networkentity (interfaces: NetworkEntity)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	net "net"

	gomock "github.com/golang/mock/gomock"
	protos "github.com/topfreegames/pitaya/v3/pkg/protos"
)

// MockNetworkEntity is a mock of NetworkEntity interface.
type MockNetworkEntity struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkEntityMockRecorder
}

// MockNetworkEntityMockRecorder is the mock recorder for MockNetworkEntity.
type MockNetworkEntityMockRecorder struct {
	mock *MockNetworkEntity
}

// NewMockNetworkEntity creates a new mock instance.
func NewMockNetworkEntity(ctrl *gomock.Controller) *MockNetworkEntity {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkEntity) EXPECT() *MockNetworkEntityMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockNetworkEntity) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockNetworkEntityMockRecorder) Close() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Kick mocks base method.
func (m *MockNetworkEntity) Kick(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Kick indicates an expected call of Kick.
func (mr *MockNetworkEntityMockRecorder) Kick(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Push mocks base method.
func (m *MockNetworkEntity) Push(arg0 string, arg1 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// Push indicates an expected call of Push.
func (mr *MockNetworkEntityMockRecorder) Push(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoteAddr mocks base method.
func (m *MockNetworkEntity) RemoteAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// RemoteAddr indicates an expected call of RemoteAddr.
func (mr *MockNetworkEntityMockRecorder) RemoteAddr() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResponseMID mocks base method.
func (m *MockNetworkEntity) ResponseMID(arg0 context.Context, arg1 uint, arg2 interface{}, arg3 ...bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ResponseMID indicates an expected call of ResponseMID.
func (mr *MockNetworkEntityMockRecorder) ResponseMID(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendRequest mocks base method.
func (m *MockNetworkEntity) SendRequest(arg0 context.Context, arg1, arg2 string, arg3 interface{}) (*protos.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SendRequest indicates an expected call of SendRequest.
func (mr *MockNetworkEntityMockRecorder) SendRequest(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
