// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/topfreegames/pitaya/v3/pkg/session (interfaces: Session,SessionPool)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	net "net"

	gomock "github.com/golang/mock/gomock"
	nats "github.com/nats-io/nats.go"
	networkentity "github.com/topfreegames/pitaya/v3/pkg/networkentity"
	session "github.com/topfreegames/pitaya/v3/pkg/session"
)

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	_ = "STUB: not implemented"

	// Bind mocks base method.
	return nil
}

func (m *MockSession) Bind(arg0 context.Context, arg1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// Bind indicates an expected call of Bind.
func (mr *MockSessionMockRecorder) Bind(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Clear mocks base method.
func (m *MockSession) Clear() { _ = "STUB: not implemented"; return }

// Clear indicates an expected call of Clear.
func (mr *MockSessionMockRecorder) Clear() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Close mocks base method.
func (m *MockSession) Close() { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MockSessionMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Float32 mocks base method.
func (m *MockSession) Float32(arg0 string) float32 { _ = "STUB: not implemented"; return 0 }

// Float32 indicates an expected call of Float32.
func (mr *MockSessionMockRecorder) Float32(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Float64 mocks base method.
func (m *MockSession) Float64(arg0 string) float64 { _ = "STUB: not implemented"; return 0 }

// Float64 indicates an expected call of Float64.
func (mr *MockSessionMockRecorder) Float64(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockSession) Get(arg0 string) interface{} { _ = "STUB: not implemented"; return nil }

// Get indicates an expected call of Get.
func (mr *MockSessionMockRecorder) Get(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetData mocks base method.
func (m *MockSession) GetData() map[string]interface{} { _ = "STUB: not implemented"; return nil }

// GetData indicates an expected call of GetData.
func (mr *MockSessionMockRecorder) GetData() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetDataEncoded mocks base method.
func (m *MockSession) GetDataEncoded() []byte { _ = "STUB: not implemented"; return nil }

// GetDataEncoded indicates an expected call of GetDataEncoded.
func (mr *MockSessionMockRecorder) GetDataEncoded() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetHandshakeData mocks base method.
func (m *MockSession) GetHandshakeData() *session.HandshakeData {
	_ = "STUB: not implemented"
	return nil
}

// GetHandshakeData indicates an expected call of GetHandshakeData.
func (mr *MockSessionMockRecorder) GetHandshakeData() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetHandshakeValidators mocks base method.
func (m *MockSession) GetHandshakeValidators() map[string]func(*session.HandshakeData) error {
	_ = "STUB: not implemented"
	return nil
}

// GetHandshakeValidators indicates an expected call of GetHandshakeValidators.
func (mr *MockSessionMockRecorder) GetHandshakeValidators() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetIsFrontend mocks base method.
func (m *MockSession) GetIsFrontend() bool { _ = "STUB: not implemented"; return false }

// GetIsFrontend indicates an expected call of GetIsFrontend.
func (mr *MockSessionMockRecorder) GetIsFrontend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOnCloseCallbacks mocks base method.
func (m *MockSession) GetOnCloseCallbacks() []func() { _ = "STUB: not implemented"; return nil }

// GetOnCloseCallbacks indicates an expected call of GetOnCloseCallbacks.
func (mr *MockSessionMockRecorder) GetOnCloseCallbacks() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRequestsInFlight mocks base method.
func (m *MockSession) GetRequestsInFlight() session.ReqInFlight {
	_ = "STUB: not implemented"
	return *new(session.ReqInFlight)
}

// GetRequestsInFlight indicates an expected call of GetRequestsInFlight.
func (mr *MockSessionMockRecorder) GetRequestsInFlight() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscriptions mocks base method.
func (m *MockSession) GetSubscriptions() []*nats.Subscription {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscriptions indicates an expected call of GetSubscriptions.
func (mr *MockSessionMockRecorder) GetSubscriptions() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HasKey mocks base method.
func (m *MockSession) HasKey(arg0 string) bool { _ = "STUB: not implemented"; return false }

// HasKey indicates an expected call of HasKey.
func (mr *MockSessionMockRecorder) HasKey(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HasRequestsInFlight mocks base method.
func (m *MockSession) HasRequestsInFlight() bool { _ = "STUB: not implemented"; return false }

// HasRequestsInFlight indicates an expected call of HasRequestsInFlight.
func (mr *MockSessionMockRecorder) HasRequestsInFlight() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ID mocks base method.
func (m *MockSession) ID() int64 { _ = "STUB: not implemented"; return 0 }

// ID indicates an expected call of ID.
func (mr *MockSessionMockRecorder) ID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Int mocks base method.
func (m *MockSession) Int(arg0 string) int { _ = "STUB: not implemented"; return 0 }

// Int indicates an expected call of Int.
func (mr *MockSessionMockRecorder) Int(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Int16 mocks base method.
func (m *MockSession) Int16(arg0 string) int16 { _ = "STUB: not implemented"; return 0 }

// Int16 indicates an expected call of Int16.
func (mr *MockSessionMockRecorder) Int16(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Int32 mocks base method.
func (m *MockSession) Int32(arg0 string) int32 { _ = "STUB: not implemented"; return 0 }

// Int32 indicates an expected call of Int32.
func (mr *MockSessionMockRecorder) Int32(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Int64 mocks base method.
func (m *MockSession) Int64(arg0 string) int64 { _ = "STUB: not implemented"; return 0 }

// Int64 indicates an expected call of Int64.
func (mr *MockSessionMockRecorder) Int64(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Int8 mocks base method.
func (m *MockSession) Int8(arg0 string) int8 { _ = "STUB: not implemented"; return 0 }

// Int8 indicates an expected call of Int8.
func (mr *MockSessionMockRecorder) Int8(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Kick mocks base method.
func (m *MockSession) Kick(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Kick indicates an expected call of Kick.
func (mr *MockSessionMockRecorder) Kick(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnClose mocks base method.
func (m *MockSession) OnClose(arg0 func()) error { _ = "STUB: not implemented"; return nil }

// OnClose indicates an expected call of OnClose.
func (mr *MockSessionMockRecorder) OnClose(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Push mocks base method.
func (m *MockSession) Push(arg0 string, arg1 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// Push indicates an expected call of Push.
func (mr *MockSessionMockRecorder) Push(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PushToFront mocks base method.
func (m *MockSession) PushToFront(arg0 context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// PushToFront indicates an expected call of PushToFront.
func (mr *MockSessionMockRecorder) PushToFront(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoteAddr mocks base method.
func (m *MockSession) RemoteAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// RemoteAddr indicates an expected call of RemoteAddr.
func (mr *MockSessionMockRecorder) RemoteAddr() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Remove mocks base method.
func (m *MockSession) Remove(arg0 string) error { _ = "STUB: not implemented"; return nil }

// Remove indicates an expected call of Remove.
func (mr *MockSessionMockRecorder) Remove(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResponseMID mocks base method.
func (m *MockSession) ResponseMID(arg0 context.Context, arg1 uint, arg2 interface{}, arg3 ...bool) error {
	_ = "STUB: not implemented"
	return nil
}

// ResponseMID indicates an expected call of ResponseMID.
func (mr *MockSessionMockRecorder) ResponseMID(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Set mocks base method.
func (m *MockSession) Set(arg0 string, arg1 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// Set indicates an expected call of Set.
func (mr *MockSessionMockRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetData mocks base method.
func (m *MockSession) SetData(arg0 map[string]interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SetData indicates an expected call of SetData.
func (mr *MockSessionMockRecorder) SetData(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDataEncoded mocks base method.
func (m *MockSession) SetDataEncoded(arg0 []byte) error { _ = "STUB: not implemented"; return nil }

// SetDataEncoded indicates an expected call of SetDataEncoded.
func (mr *MockSessionMockRecorder) SetDataEncoded(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetFrontendData mocks base method.
func (m *MockSession) SetFrontendData(arg0 string, arg1 int64) { _ = "STUB: not implemented"; return }

// SetFrontendData indicates an expected call of SetFrontendData.
func (mr *MockSessionMockRecorder) SetFrontendData(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHandshakeData mocks base method.
func (m *MockSession) SetHandshakeData(arg0 *session.HandshakeData) {
	_ = "STUB: not implemented"
	return
}

// SetHandshakeData indicates an expected call of SetHandshakeData.
func (mr *MockSessionMockRecorder) SetHandshakeData(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetIsFrontend mocks base method.
func (m *MockSession) SetIsFrontend(arg0 bool) { _ = "STUB: not implemented"; return }

// SetIsFrontend indicates an expected call of SetIsFrontend.
func (mr *MockSessionMockRecorder) SetIsFrontend(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetOnCloseCallbacks mocks base method.
func (m *MockSession) SetOnCloseCallbacks(arg0 []func()) { _ = "STUB: not implemented"; return }

// SetOnCloseCallbacks indicates an expected call of SetOnCloseCallbacks.
func (mr *MockSessionMockRecorder) SetOnCloseCallbacks(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetRequestInFlight mocks base method.
func (m *MockSession) SetRequestInFlight(arg0, arg1 string, arg2 bool) {
	_ = "STUB: not implemented"
	return
}

// SetRequestInFlight indicates an expected call of SetRequestInFlight.
func (mr *MockSessionMockRecorder) SetRequestInFlight(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetSubscriptions mocks base method.
func (m *MockSession) SetSubscriptions(arg0 []*nats.Subscription) {
	_ = "STUB: not implemented"
	return
}

// SetSubscriptions indicates an expected call of SetSubscriptions.
func (mr *MockSessionMockRecorder) SetSubscriptions(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// String mocks base method.
func (m *MockSession) String(arg0 string) string { _ = "STUB: not implemented"; return "" }

// String indicates an expected call of String.
func (mr *MockSessionMockRecorder) String(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UID mocks base method.
func (m *MockSession) UID() string { _ = "STUB: not implemented"; return "" }

// UID indicates an expected call of UID.
func (mr *MockSessionMockRecorder) UID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Uint mocks base method.
func (m *MockSession) Uint(arg0 string) uint { _ = "STUB: not implemented"; return 0 }

// Uint indicates an expected call of Uint.
func (mr *MockSessionMockRecorder) Uint(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Uint16 mocks base method.
func (m *MockSession) Uint16(arg0 string) uint16 { _ = "STUB: not implemented"; return 0 }

// Uint16 indicates an expected call of Uint16.
func (mr *MockSessionMockRecorder) Uint16(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Uint32 mocks base method.
func (m *MockSession) Uint32(arg0 string) uint32 { _ = "STUB: not implemented"; return 0 }

// Uint32 indicates an expected call of Uint32.
func (mr *MockSessionMockRecorder) Uint32(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Uint64 mocks base method.
func (m *MockSession) Uint64(arg0 string) uint64 { _ = "STUB: not implemented"; return 0 }

// Uint64 indicates an expected call of Uint64.
func (mr *MockSessionMockRecorder) Uint64(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Uint8 mocks base method.
func (m *MockSession) Uint8(arg0 string) byte { _ = "STUB: not implemented"; return 0 }

// Uint8 indicates an expected call of Uint8.
func (mr *MockSessionMockRecorder) Uint8(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateHandshake mocks base method.
func (m *MockSession) ValidateHandshake(arg0 *session.HandshakeData) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateHandshake indicates an expected call of ValidateHandshake.
func (mr *MockSessionMockRecorder) ValidateHandshake(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Value mocks base method.
func (m *MockSession) Value(arg0 string) interface{} { _ = "STUB: not implemented"; return nil }

// Value indicates an expected call of Value.
func (mr *MockSessionMockRecorder) Value(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSessionPool is a mock of SessionPool interface.
type MockSessionPool struct {
	ctrl     *gomock.Controller
	recorder *MockSessionPoolMockRecorder
}

// MockSessionPoolMockRecorder is the mock recorder for MockSessionPool.
type MockSessionPoolMockRecorder struct {
	mock *MockSessionPool
}

// NewMockSessionPool creates a new mock instance.
func NewMockSessionPool(ctrl *gomock.Controller) *MockSessionPool {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionPool) EXPECT() *MockSessionPoolMockRecorder {
	_ = "STUB: not implemented"

	// AddHandshakeValidator mocks base method.
	return nil
}

func (m *MockSessionPool) AddHandshakeValidator(arg0 string, arg1 func(*session.HandshakeData) error) {
	_ = "STUB: not implemented"
	return
}

// AddHandshakeValidator indicates an expected call of AddHandshakeValidator.
func (mr *MockSessionPoolMockRecorder) AddHandshakeValidator(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloseAll mocks base method.
func (m *MockSessionPool) CloseAll() { _ = "STUB: not implemented"; return }

// CloseAll indicates an expected call of CloseAll.
func (mr *MockSessionPoolMockRecorder) CloseAll() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNumberOfConnectedClients mocks base method.
func (m *MockSessionPool) GetNumberOfConnectedClients() int64 { _ = "STUB: not implemented"; return 0 }

// GetNumberOfConnectedClients indicates an expected call of GetNumberOfConnectedClients.
func (mr *MockSessionPoolMockRecorder) GetNumberOfConnectedClients() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ForEachSession mocks base method.
func (m *MockSessionPool) ForEachSession(arg0 func(session.Session)) {
	_ = "STUB: not implemented"
	return
}

// ForEachSession indicates an expected call of ForEachSession.
func (mr *MockSessionPoolMockRecorder) ForEachSession(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSessionByID mocks base method.
func (m *MockSessionPool) GetSessionByID(arg0 int64) session.Session {
	_ = "STUB: not implemented"
	return *new(session.Session)
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockSessionPoolMockRecorder) GetSessionByID(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSessionByUID mocks base method.
func (m *MockSessionPool) GetSessionByUID(arg0 string) session.Session {
	_ = "STUB: not implemented"
	return *new(session.Session)
}

// GetSessionByUID indicates an expected call of GetSessionByUID.
func (mr *MockSessionPoolMockRecorder) GetSessionByUID(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSessionCloseCallbacks mocks base method.
func (m *MockSessionPool) GetSessionCloseCallbacks() []func(session.Session) {
	_ = "STUB: not implemented"
	return nil
}

// GetSessionCloseCallbacks indicates an expected call of GetSessionCloseCallbacks.
func (mr *MockSessionPoolMockRecorder) GetSessionCloseCallbacks() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSessionCount mocks base method.
func (m *MockSessionPool) GetSessionCount() int64 { _ = "STUB: not implemented"; return 0 }

// GetSessionCount indicates an expected call of GetSessionCount.
func (mr *MockSessionPoolMockRecorder) GetSessionCount() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewSession mocks base method.
func (m *MockSessionPool) NewSession(arg0 networkentity.NetworkEntity, arg1 bool, arg2 ...string) session.Session {
	_ = "STUB: not implemented"
	return *new(session.Session)
}

// NewSession indicates an expected call of NewSession.
func (mr *MockSessionPoolMockRecorder) NewSession(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnAfterSessionBind mocks base method.
func (m *MockSessionPool) OnAfterSessionBind(arg0 func(context.Context, session.Session) error) {
	_ = "STUB: not implemented"
	return
}

// OnAfterSessionBind indicates an expected call of OnAfterSessionBind.
func (mr *MockSessionPoolMockRecorder) OnAfterSessionBind(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnSessionBind mocks base method.
func (m *MockSessionPool) OnSessionBind(arg0 func(context.Context, session.Session) error) {
	_ = "STUB: not implemented"
	return
}

// OnSessionBind indicates an expected call of OnSessionBind.
func (mr *MockSessionPoolMockRecorder) OnSessionBind(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnSessionClose mocks base method.
func (m *MockSessionPool) OnSessionClose(arg0 func(session.Session)) {
	_ = "STUB: not implemented"
	return
}

// OnSessionClose indicates an expected call of OnSessionClose.
func (mr *MockSessionPoolMockRecorder) OnSessionClose(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
