// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/topfreegames/pitaya/v3/pkg/metrics (interfaces: Reporter)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	_ = "STUB: not implemented"

	// ReportCount mocks base method.
	return nil
}

func (m *MockReporter) ReportCount(arg0 string, arg1 map[string]string, arg2 float64) error {
	_ = "STUB: not implemented"
	return nil
}

// ReportCount indicates an expected call of ReportCount.
func (mr *MockReporterMockRecorder) ReportCount(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReportGauge mocks base method.
func (m *MockReporter) ReportGauge(arg0 string, arg1 map[string]string, arg2 float64) error {
	_ = "STUB: not implemented"
	return nil
}

// ReportGauge indicates an expected call of ReportGauge.
func (mr *MockReporterMockRecorder) ReportGauge(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReportHistogram mocks base method.
func (m *MockReporter) ReportHistogram(arg0 string, arg1 map[string]string, arg2 float64) error {
	_ = "STUB: not implemented"
	return nil
}

// ReportHistogram indicates an expected call of ReportHistogram.
func (mr *MockReporterMockRecorder) ReportHistogram(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReportSummary mocks base method.
func (m *MockReporter) ReportSummary(arg0 string, arg1 map[string]string, arg2 float64) error {
	_ = "STUB: not implemented"
	return nil
}

// ReportSummary indicates an expected call of ReportSummary.
func (mr *MockReporterMockRecorder) ReportSummary(arg0, arg1, arg2 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
