// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/topfreegames/pitaya/v3/pkg/serialize (interfaces: Serializer)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockSerializer is a mock of Serializer interface.
type MockSerializer struct {
	ctrl     *gomock.Controller
	recorder *MockSerializerMockRecorder
}

// MockSerializerMockRecorder is the mock recorder for MockSerializer.
type MockSerializerMockRecorder struct {
	mock *MockSerializer
}

// NewMockSerializer creates a new mock instance.
func NewMockSerializer(ctrl *gomock.Controller) *MockSerializer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSerializer) EXPECT() *MockSerializerMockRecorder {
	_ = "STUB: not implemented"

	// GetName mocks base method.
	return nil
}

func (m *MockSerializer) GetName() string { _ = "STUB: not implemented"; return "" }

// GetName indicates an expected call of GetName.
func (mr *MockSerializerMockRecorder) GetName() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Marshal mocks base method.
func (m *MockSerializer) Marshal(arg0 interface{}) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Marshal indicates an expected call of Marshal.
func (mr *MockSerializerMockRecorder) Marshal(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unmarshal mocks base method.
func (m *MockSerializer) Unmarshal(arg0 []byte, arg1 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockSerializerMockRecorder) Unmarshal(arg0, arg1 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
